version: "3.8"
services:

  # Rabbit Management Queue
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Broker port
      - "15672:15672" # Management UI

  # Postgres DB
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  # App Service
  app_service:
    build: 
      context: .
      dockerfile: ./app_service/Dockerfile
    container_name: app-service
    depends_on:
      - db
      - rabbitmq
    # environment:
    #   DATABASE_URL: "${DATABASE_URL}"
    ports:
      - "8000:8000"  # Expose the app's port (adjust as needed)


  # Data Collector
  data_collector:
    build: 
      context: .
      dockerfile: ./data_collector/Dockerfile
    container_name: data-collector
    depends_on:
      - db
      - rabbitmq
    # environment:
    #   DATABASE_URL: "${DATABASE_URL}"

  # Model Service
  model_service:
    build: 
      context: .
      dockerfile: ./model_service/Dockerfile
    container_name: model-service 
    depends_on:
      - db
      - rabbitmq
    # environment:
    #   DATABASE_URL: "${DATABASE_URL}"


  # Trading Service
  trading_service:
    build: 
      context: .
      dockerfile: ./trading_service/Dockerfile
    container_name: trading-service
    depends_on:
      - db
      - rabbitmq
    # environment:
    #   DATABASE_URL: "${DATABASE_URL}"


  # Analytics Service
  analytics_service:
    build: 
      context: .
      dockerfile: ./analytics_service/Dockerfile
    container_name: analytics-service
    depends_on:
      - db
      - rabbitmq
    # environment:
    #   DATABASE_URL: "${DATABASE_URL}"

volumes:
  pgdata: